//====================================================================================================
// ASCII.Cs
// Copyright (C) 2024~ Neeko_onTheRoad
//----------------------------------------------------------------------------------------------------
// CC BY-NC
// https://creativecommons.org/licenses/by-nc/4.0/deed.en
//====================================================================================================

namespace nk.Carcassonne {
	public static class Ascii {
		public static readonly char SOH = (char)001;
		public static readonly char  BS = (char)008;
		public static readonly char  HT = (char)009;
		public static readonly char  CR = (char)013;
		public static readonly char ESC = (char)027;
		public static readonly char DEL = (char)127;
	}
}