//====================================================================================================
// $itemrootname.Cs
// Copyright (C) 2024~ Neeko_onTheRoad
//----------------------------------------------------------------------------------------------------
// CC BY-NC
// https://creativecommons.org/licenses/by-nc/4.0/deed.en
//====================================================================================================

using SFML.Graphics;

namespace nk.Carcassonne {
	public class Colors {
		public readonly static ColorSF White = new(255, 255, 255);

		public readonly static ColorSF LightPurple = new(120, 108, 198);
		public readonly static ColorSF Purple      = new(101, 53,  136);
		public readonly static ColorSF Yellow      = new(255, 247, 0  );

		public readonly static ColorSF Gray = new(25 , 25 , 25);

		public readonly static ColorSF TransparentBlack = new(0  , 0  , 0  , 150);
	}
}
