//====================================================================================================
// Program.Cs
// Copyright (C) 2024~ Neeko_onTheRoad
//----------------------------------------------------------------------------------------------------
// CC BY-NC
// https://creativecommons.org/licenses/by-nc/4.0/deed.en
//====================================================================================================

namespace nk.Carcassonne {
	public static class Program {
		public static void Main() {
			WindowBase.Init("Carcassonne", "V alpha 0.0.1");
			WindowBase.Run();
		}
	}
}
