//====================================================================================================
// $itemrootname.Cs
// Copyright (C) 2024~ Neeko_onTheRoad
//----------------------------------------------------------------------------------------------------
// CC BY-NC
// https://creativecommons.org/licenses/by-nc/4.0/deed.en
//====================================================================================================

using nk.Carcassonne;
using SFML.Graphics;

namespace nk {
	public class TextBounded : Text, IGetGlobalBounds;
}
