//====================================================================================================
// Typedef.Cs
// Copyright (C) 2024~ Neeko_onTheRoad
//----------------------------------------------------------------------------------------------------
// CC BY-NC
// https://creativecommons.org/licenses/by-nc/4.0/deed.en
//====================================================================================================

global using ColorSF     = SFML.Graphics.Color;
global using SpriteUnion = System.Collections.Generic.List<SFML.Graphics.Drawable>;
global using FontSF      = SFML.Graphics.Font;
