//====================================================================================================
// $itemrootname.Cs
// Copyright (C) 2024~ Neeko_onTheRoad
//----------------------------------------------------------------------------------------------------
// CC BY-NC
// https://creativecommons.org/licenses/by-nc/4.0/deed.en
//====================================================================================================

namespace nk.Carcassonne.Res {
	public static class Fonts {
		public static readonly FontSF Normal = new(@"Carcassonne\res\Client\Fonts\SCDream4.otf");
	}
}
