//====================================================================================================
// TileTextures.Cs
// Copyright (C) 2024~ Neeko_onTheRoad
//----------------------------------------------------------------------------------------------------
// CC BY-NC
// https://creativecommons.org/licenses/by-nc/4.0/deed.en
//====================================================================================================

namespace nk.Carcassonne {
	public class TileTextures() : IDisposable {

		void IDisposable.Dispose() {
			GC.SuppressFinalize(this);
		}

		
		
	}
}
