//====================================================================================================
// ICursorChangeable.Cs
// Copyright (C) 2024~ Neeko_onTheRoad
//----------------------------------------------------------------------------------------------------
// CC BY-NC
// https://creativecommons.org/licenses/by-nc/4.0/deed.en
//====================================================================================================

namespace nk {
	public interface ICursorChangeable {
		public bool CursorChanging { get; set; }
	}
}
